version: "3.8"

services:
  nexus:
    build:
      context: .
      dockerfile: ./packages/nexus-nodejs-docker/Dockerfile
    container_name: nexus
    ports:
      - "4000:4000"
    environment:
      - NODE_PROVIDERS=$NODE_PROVIDERS
