version: "3.8"

services:
  nexus:
    # build:
    #   context: .
    #   dockerfile: ./packages/nexus-nodejs-docker/Dockerfile
    image: "whatsgood/nexus:0.13.0"
    container_name: nexus
    ports:
      - "4000:4000"
    environment:
      - NODE_PROVIDERS=$NODE_PROVIDERS
