version: "3.8"

services:
  nexus:
    # build:
    #   context: .
    #   dockerfile: ./packages/nexus-nodejs-docker/Dockerfile
    image: "whatsgood/nexus:latest"
    container_name: nexus
    ports:
      - "4000:4000"
    environment:
      - 'NODE_PROVIDERS=[{"name": "eth.public", "url":"https://eth.public-rpc.com", "chainId": 1}]'
      - 'CHAINS=[{"name": "mainnet", "chainId": 1, "blockTime": 15}]'
      - RELAY_ORDER=random
      - RELAY_FAILURE=["cycle-requests", 5]
      - AUTH_KEY=my-secret-key
